### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by segator** [a-pavlov/jed2k#25]
* Is possible to connect to multiple trackers with same Session?
* Any way to control which search request return which responses? imagine you are executing multiple search at the same time.

**Comment by segator** [comment]
Another questions:
* trackerResultAlert.isHasMoreResults() how can I  get the list of more results?

**Comment by a-pavlov** [comment]
@segator 
* Yes if you modify source code. Currently session contains only one server connection. https://github.com/a-pavlov/jed2k/blob/8905f6c0557f56b76cdb2ed5ba1cd6a7ba0a17dd/core/src/main/java/org/dkf/jed2k/Session.java#L48
* You can not execute multiple search requests in the same server connection. Actually I didn't try it. Most likely you will have single response from the server or nothing. As you can see here each search request and response does not contain identifiers: https://github.com/a-pavlov/jed2k/blob/master/core/src/main/java/org/dkf/jed2k/protocol/server/search/SearchRequest.java and https://github.com/a-pavlov/jed2k/blob/master/core/src/main/java/org/dkf/jed2k/protocol/server/search/SearchResult.java 
* When server has returned SearchResult with moreResults != 0 you can send special request https://github.com/a-pavlov/jed2k/blob/master/core/src/main/java/org/dkf/jed2k/protocol/server/search/SearchMore.java and have search result again. Please see the correspond methods in https://github.com/a-pavlov/jed2k/blob/master/core/src/main/java/org/dkf/jed2k/ServerConnection.java - search and searchMore.

As I understand your idea your are thinking about connecting to multiple servers and run search requests in parallel. Currently this is most likely useless because of only one "good" server is TV Underground.

**Comment by segator** [comment]
Well What i'm trying to do is a rest API for ed2k(Something like newznab or torznab, ed2knab?), and I had in mind in case multiple requests come in parallel.

The final idea is add support for sickrage, couchpotato and this kind of apps.

Thanks for the answers, all clear now!!
2 more questions:
* What I don't understand is I have low ID in tracker servers and I have the ports opened.
* How can I generate nodes.dat file with the current status of the DHTTracker

**Comment by a-pavlov** [comment]
In this case you can try to open multiple connections from the same host. Needs to be tested because I did it inside Android emulators only.
* Low ID means server can not connect to your port provided on connector to server here: https://github.com/a-pavlov/jed2k/blob/8905f6c0557f56b76cdb2ed5ba1cd6a7ba0a17dd/core/src/main/java/org/dkf/jed2k/ServerConnection.java#L92.
* I guess nodes.dat is simply binary file with KAD entries inside. If it contains NodeEntry structures please see an example of saving DHT tracker state here https://github.com/a-pavlov/jed2k/blob/c11b895dba6c0cb86657c93bd3741fa5cfc7c9e1/core/src/main/java/org/dkf/jed2k/Kad2.java#L196. In that file you also can see loading of such files.

**Comment by segator** [comment]
Thanks!
