### ISSUE TITLE
Can we parse the ed2k to file download url such as http://xxxx.mp4?

### ISSUE THREAD

**Issue by kingofglory** [a-pavlov/jed2k#4]
I want to get the download url,is there anyway to do it?

**Comment by a-pavlov** [comment]
Could you explain - are you planning share file and would like to have link to it? Or you want download file using ed2k link? First case is not available since Mule on Android only downloads files. In second case you can copy ed2k link to the input field in transfers page - it will be added to transfers. Press + to show that input in transfers page.

**Comment by kingofglory** [comment]
Yeah,the first case.For example ,a ed2k link to a video file,Actually I want to watch movie online ,it's not necessary to download the whole file firstly.So I am finding a way to get the http url from the ed2k link.OK,as you say,this case is not available.Thank you for your answer.
